/**
 * 
 */
var dmaArray=["ABILENE-SWEETWATER","ALBANY, GA","ALBANY-SCHENECTADY-TROY","ALBUQUERQUE-SANTA FE","ALEXANDRIA, LA","ALPENA","AMARILLO","ANCHORAGE","ATLANTA","AUGUSTA-AIKEN","AUSTIN","BAKERSFIELD","BALTIMORE","BANGOR","BATON ROUGE","BEAUMONT-PORT ARTHUR","BEND, OR","BILLINGS","BILOXI-GULFPORT","BINGHAMTON","BIRMINGHAM (ANN AND TUSC)","BLUEFIELD-BECKLEY-OAK HILL","BOISE","BOSTON (MANCHESTER)","BOWLING GREEN","BUFFALO","BURLINGTON-PLATTSBURGH","BUTTE-BOZEMAN","CASPER-RIVERTON","CEDAR RAPIDS-WTRLO-IWC&DUB","CHAMPAIGN&SPRNGFLD-DECATUR","CHARLESTON, SC","CHARLESTON-HUNTINGTON","CHARLOTTE","CHARLOTTESVILLE","CHATTANOOGA","CHEYENNE-SCOTTSBLUF","CHICAGO","CHICO-REDDING","CINCINNATI","CLARKSBURG-WESTON","CLEVELAND-AKRON (CANTON)","COLORADO SPRINGS-PUEBLO","COLUMBIA, SC","COLUMBIA-JEFFERSON CITY","COLUMBUS, GA (OPELIKA, AL)","COLUMBUS, OH","COLUMBUS-TUPELO-W PNT-HSTN","CORPUS CHRISTI","DALLAS-FT. WORTH","DAVENPORT-R.ISLAND-MOLINE","DAYTON","DENVER","DES MOINES-AMES","DETROIT","DOTHAN","DULUTH-SUPERIOR","EL PASO (LAS CRUCES)","ELMIRA (CORNING)","ERIE","EUGENE","EUREKA","EVANSVILLE","FAIRBANKS","FARGO-VALLEY CITY","FLINT-SAGINAW-BAY CITY","FRESNO-VISALIA","FT. MYERS-NAPLES","FT. SMITH-FAY-SPRNGDL-RGRS","FT. WAYNE","GAINESVILLE","GLENDIVE","GRAND JUNCTION-MONTROSE","GRAND RAPIDS-KALMZOO-B.CRK","GREAT FALLS","GREEN BAY-APPLETON","GREENSBORO-H.POINT-W.SALEM","GREENVILLE-N.BERN-WASHNGTN","GREENVLL-SPART-ASHEVLL-AND","GREENWOOD-GREENVILLE","HARLINGEN-WSLCO-BRNSVL-MCA","HARRISBURG-LNCSTR-LEB-YORK","HARRISONBURG","HARTFORD & NEW HAVEN","HATTIESBURG-LAUREL","HELENA","HONOLULU","HOUSTON","HUNTSVILLE-DECATUR (FLOR)","IDAHO FALS-POCATLLO(JCKSN)","INDIANAPOLIS","JACKSON, MS","JACKSON, TN","JACKSONVILLE","JOHNSTOWN-ALTOONA-ST COLGE","JONESBORO","JOPLIN-PITTSBURG","JUNEAU","KANSAS CITY","KNOXVILLE","LA CROSSE-EAU CLAIRE","LAFAYETTE, IN","LAFAYETTE, LA","LAKE CHARLES","LANSING","LAREDO","LAS VEGAS","LEXINGTON","LIMA","LINCOLN & HASTINGS-KRNY","LITTLE ROCK-PINE BLUFF","LOS ANGELES","LOUISVILLE","LUBBOCK","MACON","MADISON","MANKATO","MARQUETTE","MEDFORD-KLAMATH FALLS","MEMPHIS","MERIDIAN","MIAMI-FT. LAUDERDALE","MILWAUKEE","MINNEAPOLIS-ST. PAUL","MINOT-BSMRCK-DCKNSN(WLSTN)","MISSOULA","MOBILE-PENSACOLA (FT WALT)","MONROE-EL DORADO","MONTEREY-SALINAS","MONTGOMERY-SELMA","MYRTLE BEACH-FLORENCE","NASHVILLE","NEW ORLEANS","NEW YORK","NORFOLK-PORTSMTH-NEWPT NWS","NORTH PLATTE","ODESSA-MIDLAND","OKLAHOMA CITY","OMAHA","ORLANDO-DAYTONA BCH-MELBRN","OTTUMWA-KIRKSVILLE","PADUCAH-CAPE GIRARD-HARSBG","PALM SPRINGS","PANAMA CITY","PARKERSBURG","PEORIA-BLOOMINGTON","PHILADELPHIA","PHOENIX (PRESCOTT)","PITTSBURGH","PORTLAND, OR","PORTLAND-AUBURN","PRESQUE ISLE","PROVIDENCE-NEW BEDFORD","QUINCY-HANNIBAL-KEOKUK","RALEIGH-DURHAM (FAYETVLLE)","RAPID CITY","RENO","RICHMOND-PETERSBURG","ROANOKE-LYNCHBURG","ROCHESTER, NY","ROCHESTR-MASON CITY-AUSTIN","ROCKFORD","SACRAMNTO-STKTON-MODESTO","SALISBURY","SALT LAKE CITY","SAN ANGELO","SAN ANTONIO","SAN DIEGO","SAN FRANCISCO-OAK-SAN JOSE","SANTABARBRA-SANMAR-SANLUOB","SAVANNAH","SEATTLE-TACOMA","SHERMAN-ADA","SHREVEPORT","SIOUX CITY","SIOUX FALLS(MITCHELL)","SOUTH BEND-ELKHART","SPOKANE","SPRINGFIELD, MO","SPRINGFIELD-HOLYOKE","ST. JOSEPH","ST. LOUIS","SYRACUSE","TALLAHASSEE-THOMASVILLE","TAMPA-ST. PETE (SARASOTA)","TERRE HAUTE","TOLEDO","TOPEKA","TRAVERSE CITY-CADILLAC","TRI-CITIES, TN-VA","TUCSON (SIERRA VISTA)","TULSA","TWIN FALLS","TYLER-LONGVIEW(LFKN&NCGD)","UTICA","VICTORIA","WACO-TEMPLE-BRYAN","WASHINGTON, DC (HAGRSTWN)","WATERTOWN","WAUSAU-RHINELANDER","WEST PALM BEACH-FT. PIERCE","WHEELING-STEUBENVILLE","WICHITA FALLS & LAWTON","WICHITA-HUTCHINSON PLUS","WILKES BARRE-SCRANTON-HZTN","WILMINGTON","YAKIMA-PASCO-RCHLND-KNNWCK","YOUNGSTOWN","YUMA-EL CENTRO","ZANESVILLE"];
var categories_dma=["ABILENE-SWEETWATER","ALBANY, GA","ALBANY-SCHENECTADY-TROY","ALBUQUERQUE-SANTA FE","ALEXANDRIA, LA"];// distance category of chart
//categories_dma=[];

var dmaFilterDialog=new contentDialog();
dmaFilterDialog.setTitle("DMA Filter");
dmaFilterDialog.setWidth(800);

//install dma list
var dmaDialogContent=$('<div></div>');
$.each(dmaArray, function(index,item){
	var fistChart=item.substring(0,2);
	var lastChart=item.substring(2);
	var div=$('<button style="margin: 2px;text-transform: lowercase;" type="button" class="btn btn-default btn-xs"><span style="font-size: 12pt;font-weight:bold;text-transform: uppercase;">'+fistChart+'</span>'+lastChart+'</button>');
	div.click(function(){
		if($(this).hasClass( "btn-default" )){
			$(this).removeClass("btn-default");
			$(this).addClass("btn-warning");
			categories_dma.push(item);
		}else{
			$(this).removeClass("btn-warning");
			$(this).addClass("btn-default");
			categories_dma.splice(categories_dma.indexOf(item),1);
		}
	});
	if(categories_dma.indexOf(item)>=0){
		div.removeClass("btn-default");
		div.addClass("btn-warning");
	}
	dmaDialogContent.append(div);
});
dmaFilterDialog.setContent(dmaDialogContent);
dmaFilterDialog.acceptFunction(function(){
	categories_dma.sort();
	alert(categories_dma.join(";"));
});
dmaFilterDialog.setAcceptBtnName("View Chart");
$("#dmaFilterBtn").click(function(){
	dmaFilterDialog.open();	
});
function loadChartByDma(){
	if(categories_dma.length==0){
		alert("Select Dma to generate the chart!");
		dmaFilterDialog.open();
		return;
	}
	
}